function outputPath = build_matlab_polycall(varargin)
%BUILD_MATLAB_POLYCALL Build the MEX gateway.
% Pass the libpolycall import/static library, followed by optional mex flags.

root = fileparts(mfilename("fullpath"));
outputDirectory = fullfile(root, "lib");
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

mex("-R2018a", ...
    "-I" + fullfile(root, "include"), ...
    "-I" + fullfile(root, "generated"), ...
    fullfile(root, "src", "matlab_polycall_mex.c"), ...
    fullfile(root, "src", "matlab_polycall.c"), ...
    varargin{:}, ...
    "-outdir", outputDirectory, ...
    "-output", "matlab_polycall_mex");

outputPath = fullfile(outputDirectory, "matlab_polycall_mex." + mexext);
end
